id: P001713
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1AC393
  title: ཙ་རིའི་གནས་ཡིག
  author: ''
  volumes:
    9ed4deb3ff7040a9883ac91b8128f7de:
      image_group_id: I2PD18772
      title: ''
      volume_number: 1
      total_pages: 114
      base_file: v001.txt
